// <auto-generated />
using System;
using FeedbackFriend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FeedbackFriend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FeedbackFriend.Models.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("QuestionId");

                    b.Property<int>("ResponderId");

                    b.Property<int>("Response");

                    b.Property<string>("UserId");

                    b.Property<int>("UserSurveyId");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserSurveyId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("FeedbackFriend.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "cd684c07-1c9d-4caf-be86-7d21ca7493b3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6c1d0572-0df9-4af1-8988-38a63f937678",
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            FirstName = "admin",
                            LastName = "admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEO4VNgfMImKwPapvBHQrZOi0ur4mM0o19lswtZ4PgfxCB9BLLB6J6GDhjuR0kZaMXg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "75897d61-b21f-42f9-91b8-e98d4a6ef575",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com"
                        });
                });

            modelBuilder.Entity("FeedbackFriend.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("QuestionText")
                        .IsRequired();

                    b.Property<int>("SurveyId");

                    b.HasKey("QuestionId");

                    b.HasIndex("SurveyId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            QuestionText = "In your experience, is this person attentive to the schedules of others?",
                            SurveyId = 1
                        },
                        new
                        {
                            QuestionId = 2,
                            QuestionText = "In your experience, what is this person's level of focus on company objectives?",
                            SurveyId = 1
                        },
                        new
                        {
                            QuestionId = 3,
                            QuestionText = "In your experience, what is this person's level of focus on measuring appreciable progress toward company objectives?",
                            SurveyId = 1
                        },
                        new
                        {
                            QuestionId = 4,
                            QuestionText = "In your experience, how informed is this person about the responsibilities and job scope of others?",
                            SurveyId = 1
                        },
                        new
                        {
                            QuestionId = 5,
                            QuestionText = "In your experience, how attuned is this person to the likely stress points of their co-workers?",
                            SurveyId = 1
                        },
                        new
                        {
                            QuestionId = 6,
                            QuestionText = "In your experience, how attuned is this person to the values of others?",
                            SurveyId = 1
                        },
                        new
                        {
                            QuestionId = 7,
                            QuestionText = "In your experience, how attuned is this person to the communication styles of others?",
                            SurveyId = 1
                        },
                        new
                        {
                            QuestionId = 8,
                            QuestionText = "In your experience, how insistent is this person that others adapt to their communication style?",
                            SurveyId = 1
                        },
                        new
                        {
                            QuestionId = 9,
                            QuestionText = "In your experience, how insistent is this person that others adapt to their problem solving style?",
                            SurveyId = 1
                        },
                        new
                        {
                            QuestionId = 10,
                            QuestionText = "In your experience, how responsive is this person to decreases in momentum during meetings?",
                            SurveyId = 1
                        },
                        new
                        {
                            QuestionId = 11,
                            QuestionText = "In your experience, is this person aware of, and responsive to the level of team morale?",
                            SurveyId = 1
                        },
                        new
                        {
                            QuestionId = 12,
                            QuestionText = "In your experience, what is their capacity for seeing differing opinions as complimentary rather than adversarial?",
                            SurveyId = 1
                        },
                        new
                        {
                            QuestionId = 13,
                            QuestionText = "In your experience, how attentively did this person listen?",
                            SurveyId = 2
                        },
                        new
                        {
                            QuestionId = 14,
                            QuestionText = "In your experience, was this person easily distracted?",
                            SurveyId = 2
                        },
                        new
                        {
                            QuestionId = 15,
                            QuestionText = "In your experience, did this person acknowledge the concerns of others?",
                            SurveyId = 2
                        },
                        new
                        {
                            QuestionId = 16,
                            QuestionText = "In your experience, did this person validate the concerns of others?",
                            SurveyId = 2
                        },
                        new
                        {
                            QuestionId = 17,
                            QuestionText = "In your experience, did this person show appreciation for the strengths/pros of others' points of view?",
                            SurveyId = 2
                        },
                        new
                        {
                            QuestionId = 18,
                            QuestionText = "In your experience, was this person attentive to what wasn't being said?",
                            SurveyId = 2
                        },
                        new
                        {
                            QuestionId = 19,
                            QuestionText = "In your experience, did this person take time to understand and validate other points of view before offering solutions?",
                            SurveyId = 2
                        },
                        new
                        {
                            QuestionId = 20,
                            QuestionText = "In your experience, what percentage of this person's time was spent listening? (Where 1 = 10% and 10 = 100%)",
                            SurveyId = 2
                        },
                        new
                        {
                            QuestionId = 21,
                            QuestionText = "In your experience, what is this person's capacity for productive silence?",
                            SurveyId = 2
                        },
                        new
                        {
                            QuestionId = 22,
                            QuestionText = "In your experience, does this person stop talking after realizing they're interrupting?",
                            SurveyId = 3
                        },
                        new
                        {
                            QuestionId = 23,
                            QuestionText = "In your experience, does this person stop talking when they're becoming repetitive?",
                            SurveyId = 3
                        },
                        new
                        {
                            QuestionId = 24,
                            QuestionText = "In your experience, how likely is this person to pursue the same conversation again and again?",
                            SurveyId = 3
                        },
                        new
                        {
                            QuestionId = 25,
                            QuestionText = "In your experience, how much attunement does this person show to others' receptivity?",
                            SurveyId = 3
                        },
                        new
                        {
                            QuestionId = 26,
                            QuestionText = "In your experience, is this person likely to stop talking in order to negotiate time to compose a thoughtful response?",
                            SurveyId = 3
                        },
                        new
                        {
                            QuestionId = 27,
                            QuestionText = "In your experience, what is this person's capacity to create a refuge of silence when others are being unreasonable or irrational?",
                            SurveyId = 3
                        },
                        new
                        {
                            QuestionId = 28,
                            QuestionText = "In your experience, does this person stop talking when the focus of the group shifts from the topic at hand?",
                            SurveyId = 3
                        },
                        new
                        {
                            QuestionId = 29,
                            QuestionText = "In your experience, does this person have a tendency to offer unsolicited advice?",
                            SurveyId = 3
                        },
                        new
                        {
                            QuestionId = 30,
                            QuestionText = "In your experience, does this person have a tendency to offer unsolicited critique?",
                            SurveyId = 3
                        },
                        new
                        {
                            QuestionId = 31,
                            QuestionText = "In your experience, how likely is this person to substitute conversation for action - suffer from the paralysis of analysis?",
                            SurveyId = 3
                        },
                        new
                        {
                            QuestionId = 32,
                            QuestionText = "In your experience, how likely is this person to agree with and act on the phrase, 'Delay is the deadliest form of denial'?",
                            SurveyId = 3
                        },
                        new
                        {
                            QuestionId = 33,
                            QuestionText = "In your opinion, how informative was this presentation?",
                            SurveyId = 4
                        },
                        new
                        {
                            QuestionId = 34,
                            QuestionText = "In your experience, how successful was this person in communicating context?",
                            SurveyId = 4
                        },
                        new
                        {
                            QuestionId = 35,
                            QuestionText = "In your experience, how successful was this person in communicating expectations for action/response?",
                            SurveyId = 4
                        },
                        new
                        {
                            QuestionId = 36,
                            QuestionText = "How positively did you experience this person's nonverbal communication?",
                            SurveyId = 4
                        },
                        new
                        {
                            QuestionId = 37,
                            QuestionText = "How positively did you experience this person's tone of voice?",
                            SurveyId = 4
                        },
                        new
                        {
                            QuestionId = 38,
                            QuestionText = "In your experience, did this person maintain a good balance between talking and listening?",
                            SurveyId = 4
                        },
                        new
                        {
                            QuestionId = 39,
                            QuestionText = "In your experience, was this person dismissive of other's concerns?",
                            SurveyId = 4
                        },
                        new
                        {
                            QuestionId = 40,
                            QuestionText = "In your opinion, did the presentation meet its stated objectives?",
                            SurveyId = 4
                        },
                        new
                        {
                            QuestionId = 41,
                            QuestionText = "In your experience, did this person deal well with distractions?",
                            SurveyId = 4
                        },
                        new
                        {
                            QuestionId = 42,
                            QuestionText = "In your opinion, did the presentation wander off course?",
                            SurveyId = 4
                        },
                        new
                        {
                            QuestionId = 43,
                            QuestionText = "In your opinion, was the pace of the presentation hurried?",
                            SurveyId = 4
                        },
                        new
                        {
                            QuestionId = 44,
                            QuestionText = "In your opinion, was preparation for this presentation in evidence?",
                            SurveyId = 4
                        },
                        new
                        {
                            QuestionId = 45,
                            QuestionText = "In your opinion, was there mastery of the subject matter?",
                            SurveyId = 4
                        },
                        new
                        {
                            QuestionId = 46,
                            QuestionText = "In your opinion, was the material organized?",
                            SurveyId = 4
                        },
                        new
                        {
                            QuestionId = 47,
                            QuestionText = "In your experience, did this person maintain good eye contact?",
                            SurveyId = 4
                        },
                        new
                        {
                            QuestionId = 48,
                            QuestionText = "In your experience, was this person's posture open, relaxed and receptive?",
                            SurveyId = 4
                        },
                        new
                        {
                            QuestionId = 49,
                            QuestionText = "In your experience, did this person fidget and/or have other distracting gestures?",
                            SurveyId = 4
                        },
                        new
                        {
                            QuestionId = 50,
                            QuestionText = "In your experience, what was this person's level of defensiveness relative to questions?",
                            SurveyId = 4
                        },
                        new
                        {
                            QuestionId = 51,
                            QuestionText = "In your experience, how much did this person seek to understand others before being understood?",
                            SurveyId = 4
                        },
                        new
                        {
                            QuestionId = 52,
                            QuestionText = "In your experience, how flexible was this person in reframing difficult interactions?",
                            SurveyId = 4
                        },
                        new
                        {
                            QuestionId = 53,
                            QuestionText = "In your experience, to what degree were they able to recognize and affirm what others valued?",
                            SurveyId = 4
                        },
                        new
                        {
                            QuestionId = 54,
                            QuestionText = "In your experience, how likely is this person to say, 'Let's do it now'?",
                            SurveyId = 5
                        },
                        new
                        {
                            QuestionId = 55,
                            QuestionText = "In your experience, how likely is this person to say, 'Let's give it some time'?",
                            SurveyId = 5
                        },
                        new
                        {
                            QuestionId = 56,
                            QuestionText = "How likely are you to describe this person as a self-starter, bold, determined and tenacious?",
                            SurveyId = 5
                        },
                        new
                        {
                            QuestionId = 57,
                            QuestionText = "How likely are you to describe this person as considerate, self-controlled, patient and cooperative?",
                            SurveyId = 5
                        },
                        new
                        {
                            QuestionId = 58,
                            QuestionText = "In your experience, does this person become intimidating and confrontational in the midst of conflict?",
                            SurveyId = 5
                        },
                        new
                        {
                            QuestionId = 59,
                            QuestionText = "In your experience, does this person become anxious, slow, or withdrawn in the midst of conflict?",
                            SurveyId = 5
                        },
                        new
                        {
                            QuestionId = 60,
                            QuestionText = "In your experience, does this person display irritation when interrupted?",
                            SurveyId = 5
                        },
                        new
                        {
                            QuestionId = 61,
                            QuestionText = "In your experience, does this person listen as slowly as they speak?",
                            SurveyId = 5
                        },
                        new
                        {
                            QuestionId = 62,
                            QuestionText = "Do you experience this person as direct?",
                            SurveyId = 5
                        },
                        new
                        {
                            QuestionId = 63,
                            QuestionText = "Do you experience this person as apt to waste time and resources?",
                            SurveyId = 5
                        },
                        new
                        {
                            QuestionId = 64,
                            QuestionText = "Do you experience this person as indecisive?",
                            SurveyId = 5
                        },
                        new
                        {
                            QuestionId = 65,
                            QuestionText = "Do you experience this person as valuing function over relationship - achieving goals over valuing people?",
                            SurveyId = 5
                        },
                        new
                        {
                            QuestionId = 66,
                            QuestionText = "In your experience, is this person adept at gathering information?",
                            SurveyId = 5
                        },
                        new
                        {
                            QuestionId = 67,
                            QuestionText = "In your experience, does this person miss opportunities?",
                            SurveyId = 5
                        },
                        new
                        {
                            QuestionId = 68,
                            QuestionText = "In your experience, how likely is this person to say, 'We could solve this problem if you'd do what I say'?",
                            SurveyId = 5
                        },
                        new
                        {
                            QuestionId = 69,
                            QuestionText = "Do you experience this person as more objective than subjective?",
                            SurveyId = 5
                        },
                        new
                        {
                            QuestionId = 70,
                            QuestionText = "To what extent do you experience this person as inattentive - Do they miss what others value?",
                            SurveyId = 6
                        },
                        new
                        {
                            QuestionId = 71,
                            QuestionText = "To what extent do you experience this person as unreliable?",
                            SurveyId = 6
                        },
                        new
                        {
                            QuestionId = 72,
                            QuestionText = "To what extent do you experience this person as optimistic and enthusiastic?",
                            SurveyId = 6
                        },
                        new
                        {
                            QuestionId = 73,
                            QuestionText = "To what extent do you experience this person as an adept negotiator?",
                            SurveyId = 6
                        },
                        new
                        {
                            QuestionId = 74,
                            QuestionText = "How likely is this person to say, 'Trust me, it will work great'?",
                            SurveyId = 6
                        },
                        new
                        {
                            QuestionId = 75,
                            QuestionText = "How likely is this person to say, 'Let's stop and look at all the evidence'?",
                            SurveyId = 6
                        },
                        new
                        {
                            QuestionId = 76,
                            QuestionText = "To what extent do you experience this person as calm and introspective?",
                            SurveyId = 6
                        },
                        new
                        {
                            QuestionId = 77,
                            QuestionText = "To what extent do you experience this person as friendly and outgoing?",
                            SurveyId = 6
                        },
                        new
                        {
                            QuestionId = 78,
                            QuestionText = "In your experience of them, does this person become impulsive and unrealistic when under stress?",
                            SurveyId = 6
                        },
                        new
                        {
                            QuestionId = 79,
                            QuestionText = "In your experience of them, does this person become pessimistic and introspective when under stress?",
                            SurveyId = 6
                        },
                        new
                        {
                            QuestionId = 80,
                            QuestionText = "In your experience of them, does this person become skeptical and uncommunicative in the midst of conflict?",
                            SurveyId = 6
                        },
                        new
                        {
                            QuestionId = 81,
                            QuestionText = "In your experience of them, does this person become a poor listener in the midst of conflict?",
                            SurveyId = 6
                        },
                        new
                        {
                            QuestionId = 82,
                            QuestionText = "To what degree do you experience this person as inspiring?",
                            SurveyId = 6
                        },
                        new
                        {
                            QuestionId = 83,
                            QuestionText = "How likely is this person to say, 'Let's keep things the way they are'?",
                            SurveyId = 7
                        },
                        new
                        {
                            QuestionId = 84,
                            QuestionText = "How likely is this person to say, 'Let's try something new'?",
                            SurveyId = 7
                        },
                        new
                        {
                            QuestionId = 85,
                            QuestionText = "To what degree do you experience this person as a team-player?",
                            SurveyId = 7
                        },
                        new
                        {
                            QuestionId = 86,
                            QuestionText = "To what degree do you experience this person as methodical?",
                            SurveyId = 7
                        },
                        new
                        {
                            QuestionId = 87,
                            QuestionText = "To what degree do you experience them as energetic?",
                            SurveyId = 7
                        },
                        new
                        {
                            QuestionId = 88,
                            QuestionText = "To what degree do you experience them as spontaneous?",
                            SurveyId = 7
                        },
                        new
                        {
                            QuestionId = 89,
                            QuestionText = "To what degree do you experience them as flexible?",
                            SurveyId = 7
                        },
                        new
                        {
                            QuestionId = 90,
                            QuestionText = "In your experience, does this person become slow-paced and inflexible under stress?",
                            SurveyId = 7
                        },
                        new
                        {
                            QuestionId = 91,
                            QuestionText = "In your experience, does this person become more intense and reckless under stress?",
                            SurveyId = 7
                        },
                        new
                        {
                            QuestionId = 92,
                            QuestionText = "In your experience, does this person tend toward sullen and stubborn in the midst of conflict?",
                            SurveyId = 7
                        },
                        new
                        {
                            QuestionId = 93,
                            QuestionText = "In your experience, does this person become distracted and impulsive in the midst of conflict?",
                            SurveyId = 7
                        },
                        new
                        {
                            QuestionId = 94,
                            QuestionText = "How likely is this person to say, 'I'm not sure yet'?",
                            SurveyId = 8
                        },
                        new
                        {
                            QuestionId = 95,
                            QuestionText = "How likely is this person to say, 'Let's go for it'?",
                            SurveyId = 8
                        },
                        new
                        {
                            QuestionId = 96,
                            QuestionText = "To what degree do you experience this person as conscientious?",
                            SurveyId = 8
                        },
                        new
                        {
                            QuestionId = 97,
                            QuestionText = "To what degree do you experience this person as bold?",
                            SurveyId = 8
                        },
                        new
                        {
                            QuestionId = 98,
                            QuestionText = "To what degree do you experience this person as having high standards?",
                            SurveyId = 8
                        },
                        new
                        {
                            QuestionId = 99,
                            QuestionText = "To what degree do you experience this person as decisive?",
                            SurveyId = 8
                        },
                        new
                        {
                            QuestionId = 100,
                            QuestionText = "To what degree do you experience this person as accurate?",
                            SurveyId = 8
                        },
                        new
                        {
                            QuestionId = 101,
                            QuestionText = "To what degree do you experience this person as independent?",
                            SurveyId = 8
                        },
                        new
                        {
                            QuestionId = 102,
                            QuestionText = "In your experience, does this person become more exacting and perfectionistic when under stress?",
                            SurveyId = 8
                        },
                        new
                        {
                            QuestionId = 103,
                            QuestionText = "In your experience, does this person become more controversial and insensitive when under stress?",
                            SurveyId = 8
                        },
                        new
                        {
                            QuestionId = 104,
                            QuestionText = "In your experience, does this person become more indecisive and unyielding in the midst of conflict?",
                            SurveyId = 8
                        },
                        new
                        {
                            QuestionId = 105,
                            QuestionText = "In your experience, does this person become more reckless and overconfident when in the midst of conflict?",
                            SurveyId = 8
                        });
                });

            modelBuilder.Entity("FeedbackFriend.Models.Survey", b =>
                {
                    b.Property<int>("SurveyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Instructions");

                    b.Property<string>("SurveyName")
                        .IsRequired()
                        .HasMaxLength(55);

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("SurveyId");

                    b.HasIndex("UserId");

                    b.ToTable("Surveys");

                    b.HasData(
                        new
                        {
                            SurveyId = 1,
                            Description = "The primary objective of this survey is to collect feedback relative to a person's capacity for walking in another's shoes and how others experience their balance of analysis and sympathy.",
                            Instructions = "Responses are on a scale of 1 - 10 where 1 is never/little/strongly disagree and 10 is always/much/strongly agree. Consider your experience of this individual relative to the way they balance analysis and sympathy and relative to your experience of their capacity for walking in another's shoes.",
                            SurveyName = "Empathy",
                            UserId = "cd684c07-1c9d-4caf-be86-7d21ca7493b3"
                        },
                        new
                        {
                            SurveyId = 2,
                            Description = "The primary objective of this survey is twofold. 1. To collect feedback relative to a persons' capacity for passive hearing vs active listening. 2. To asses their attunement to the reality that it's not about what we tell people, but what they hear.",
                            Instructions = "Responses are on a scale of 1 - 10 where 1 is never/little/strongly disagree and 10 is always/much/strongly agree.",
                            SurveyName = "Listening vs hearing",
                            UserId = "cd684c07-1c9d-4caf-be86-7d21ca7493b3"
                        },
                        new
                        {
                            SurveyId = 3,
                            Description = "The primary objective of this survey is to assess flexibility and responsiveness in communication.",
                            Instructions = "Responses are on a scale of 1 - 10 where 1 is never/little/strongly disagree and 10 is always/much/strongly agree.",
                            SurveyName = "Just stop talking already",
                            UserId = "cd684c07-1c9d-4caf-be86-7d21ca7493b3"
                        },
                        new
                        {
                            SurveyId = 4,
                            Description = "The primary objective of this survey is to assess capacity for navigating emotional safety needs. How did this person balance the need to avoid pain and potential loss of what they value, danger and insecurity with the objective they were committed to?",
                            Instructions = "Responses are on a scale of 1 - 10 where 1 is never/little/strongly disagree and 10 is always/much/strongly agree.",
                            SurveyName = "Presentation Feedback",
                            UserId = "cd684c07-1c9d-4caf-be86-7d21ca7493b3"
                        },
                        new
                        {
                            SurveyId = 5,
                            Description = "The primary objective of this survey is to assess the balance between approaching problems aggressively vs reflectively. How much does the need to gain control of one's time factor in problem solving?",
                            Instructions = "Responses are on a scale of 1 - 10 where 1 is never/little/strongly disagree and 10 is always/much/strongly agree.",
                            SurveyName = "Problem Solving",
                            UserId = "cd684c07-1c9d-4caf-be86-7d21ca7493b3"
                        },
                        new
                        {
                            SurveyId = 6,
                            Description = "What is this person's style of influence? Primarily feeling, or fact? Can they move flexibly between them when it's called for? How much does the need to gain approval factor in their style of influence?",
                            Instructions = "Responses are on a scale of 1 - 10 where 1 is never/little/strongly disagree and 10 is always/much/strongly agree.",
                            SurveyName = "Influence",
                            UserId = "cd684c07-1c9d-4caf-be86-7d21ca7493b3"
                        },
                        new
                        {
                            SurveyId = 7,
                            Description = "The primary objective of this survey is to assess the balance between necessary stability and unnecessary resistance to change - Does this person prefer the certainty of misery or the misery of uncertainty?",
                            Instructions = "Responses are on a scale of 1 - 10 where 1 is never/little/strongly disagree and 10 is always/much/strongly agree.",
                            SurveyName = "Change",
                            UserId = "cd684c07-1c9d-4caf-be86-7d21ca7493b3"
                        },
                        new
                        {
                            SurveyId = 8,
                            Description = "The primary objective of this survey is to assess caution vs spontaneity in the quest for excellence. How does this person live in the time warp between carefully weighing options and possibly missing opportunities?",
                            Instructions = "Responses are on a scale of 1 - 10 where 1 is never/little/strongly disagree and 10 is always/much/strongly agree.",
                            SurveyName = "Decision Making",
                            UserId = "cd684c07-1c9d-4caf-be86-7d21ca7493b3"
                        });
                });

            modelBuilder.Entity("FeedbackFriend.Models.UserSurvey", b =>
                {
                    b.Property<int>("UserSurveyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FocusId");

                    b.Property<int>("ResponderId");

                    b.Property<int>("SurveyId");

                    b.Property<string>("UserId");

                    b.HasKey("UserSurveyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSurvey");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("FeedbackFriend.Models.Answer", b =>
                {
                    b.HasOne("FeedbackFriend.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FeedbackFriend.Models.ApplicationUser", "User")
                        .WithMany("Answers")
                        .HasForeignKey("UserId");

                    b.HasOne("FeedbackFriend.Models.UserSurvey", "UserSurvey")
                        .WithMany()
                        .HasForeignKey("UserSurveyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FeedbackFriend.Models.Question", b =>
                {
                    b.HasOne("FeedbackFriend.Models.Survey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FeedbackFriend.Models.Survey", b =>
                {
                    b.HasOne("FeedbackFriend.Models.ApplicationUser", "User")
                        .WithMany("Surveys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FeedbackFriend.Models.UserSurvey", b =>
                {
                    b.HasOne("FeedbackFriend.Models.ApplicationUser", "User")
                        .WithMany("UserSurveys")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FeedbackFriend.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FeedbackFriend.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FeedbackFriend.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FeedbackFriend.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
